import styled from "styled-components";

export default function HomeContent() {
  return (
    <Container>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed egestas risus eu dui aliquet, in sodales dolor feugiat. Donec gravida, erat sed elementum euismod, quam justo condimentum nunc, nec euismod purus sem vel ex. In hac habitasse platea dictumst. Sed suscipit hendrerit odio, vel efficitur tellus molestie ac. In posuere est a tellus porttitor aliquam. Sed dictum tellus eu metus lobortis rhoncus eu ut odio. Sed at eros non tellus sagittis vulputate. Nam ipsum nisi, tincidunt sed urna vel, vulputate dignissim velit. Ut aliquam lacinia est, ac tempus lacus tincidunt convallis.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam luctus quis dolor efficitur mattis. Morbi efficitur est est, quis ullamcorper nunc congue ut. Aenean eleifend et leo ut molestie. In lacus justo, ullamcorper quis iaculis non, commodo vitae ex. Ut commodo dui ac maximus efficitur. Sed sit amet dolor sed ipsum mollis porta sed vitae tellus. Vivamus laoreet felis justo, id malesuada turpis tempor tincidunt. Duis faucibus maximus sem sed pellentesque. Donec dictum sed dolor ut placerat. Mauris ac fringilla augue. Integer lobortis lacus lobortis ligula placerat, eget mattis sapien porttitor.

Proin diam enim, efficitur non posuere et, tempor facilisis nisi. Aliquam molestie mauris et quam bibendum consectetur. Aliquam suscipit tincidunt velit eu cursus. Praesent nec cursus enim. Nunc urna lorem, pretium ac pretium congue, vehicula in nisl. Donec a ante non lorem imperdiet malesuada. Donec bibendum pretium ex. Curabitur eget eros ac nisi maximus sodales in vel lectus. Nullam eu odio auctor, dignissim justo sed, laoreet lectus. Aenean vitae leo facilisis sem posuere placerat id a ex.

Pellentesque ex justo, vulputate vitae neque a, commodo mattis tortor. Praesent vitae blandit sapien. Integer aliquam pharetra erat vitae sodales. Donec lacinia felis nec rhoncus malesuada. Pellentesque tortor arcu, consequat eu mi vel, mattis condimentum nunc. Curabitur lacus ligula, lacinia id aliquet in, dignissim eget sapien. Vestibulum non dignissim orci, ac laoreet ligula. Duis nec dictum nisl, non blandit diam. Duis id iaculis ante.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus finibus dignissim lectus ac feugiat. Duis euismod felis eu turpis eleifend interdum. Maecenas libero nunc, vestibulum et sapien eu, sollicitudin facilisis justo. Pellentesque convallis mi arcu. Sed fermentum nibh non nulla condimentum viverra. Fusce eu ante enim. Donec augue augue, ultricies at leo vel, tempus viverra tortor. Nullam nunc turpis, finibus id pharetra ornare, pretium imperdiet eros. Donec ut justo at urna feugiat pulvinar eu et eros. Morbi ullamcorper metus condimentum, tempor magna at, laoreet odio.

Praesent a tincidunt leo. Mauris ornare libero ac magna posuere accumsan. Nulla ut interdum justo. Maecenas rhoncus eu velit ut sollicitudin. Etiam tortor elit, blandit sit amet turpis sit amet, fringilla eleifend lectus. Phasellus dapibus orci bibendum tristique ultrices. In nec lacinia orci. Integer a massa a tellus ornare facilisis sit amet vitae velit. Vestibulum in dolor at orci laoreet vehicula. Donec vel justo et magna interdum placerat. Maecenas venenatis nec justo non dapibus. Fusce nec porta odio. Sed vitae maximus dui. Vivamus semper augue et neque auctor egestas. Nulla nec convallis lacus.

Donec et mattis lorem. Nullam eget odio vitae diam laoreet sollicitudin et eu libero. Etiam eros nisi, suscipit vitae lacinia nec, dignissim id leo. Nam dapibus sit amet leo et laoreet. Nullam convallis mauris nec sem placerat, a finibus nibh pharetra. Integer vitae scelerisque metus, id efficitur nisl. In venenatis sodales diam, at tempus mauris fringilla ut. Integer mattis dui eget lorem congue, nec pharetra lorem fermentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eros eros, venenatis et egestas sed, facilisis id nibh. Etiam congue, lorem auctor faucibus tempor, mauris risus fringilla ligula, ac suscipit lectus lorem sed magna. Duis eu commodo metus. Proin in risus augue.

Vivamus et orci at lectus ultricies aliquam. Quisque egestas ligula in magna ultricies, tempus mollis ex ultricies. Ut rutrum hendrerit posuere. Nullam volutpat diam sit amet odio aliquet bibendum. Maecenas sodales, enim vitae congue laoreet, lectus enim molestie sapien, quis commodo ante diam id ligula. Suspendisse efficitur feugiat mi, id pharetra arcu lobortis eget. Quisque in nisl hendrerit, mattis risus vitae, vehicula massa. Quisque elementum et elit quis fermentum. Integer blandit risus at nibh cursus cursus. Mauris id vestibulum quam, eu consectetur dui. Cras placerat luctus tortor eu aliquam. Aliquam auctor ante eget semper condimentum. Aenean nec lectus nec ante tristique pellentesque nec at massa. Morbi vel felis urna. Vivamus eu ligula vitae enim placerat faucibus.

Maecenas laoreet dapibus diam eu hendrerit. Curabitur molestie efficitur mi id iaculis. Mauris nec nunc quam. Sed sem lacus, finibus at nunc nec, aliquet sagittis magna. Quisque at nunc ac augue scelerisque interdum. Nunc eget molestie leo. Cras massa enim, venenatis a est at, bibendum tincidunt lorem. Nulla sit amet libero ultrices, congue magna ut, sollicitudin enim. Nam eget eros non ex egestas euismod sed ac velit. Nam a turpis ut nulla eleifend sollicitudin.

Morbi feugiat magna ornare mollis maximus. Nullam semper ex ligula, nec posuere mi tempus quis. Morbi efficitur convallis euismod. Vivamus dui nibh, ultrices eu ullamcorper et, volutpat euismod diam. In a facilisis elit. Vestibulum laoreet, turpis ut elementum vulputate, nisl nibh volutpat urna, at lobortis lacus risus eget turpis. Morbi ac convallis mauris.

Aliquam in massa a quam lacinia iaculis. Maecenas sollicitudin odio ligula, a ullamcorper magna congue eget. Integer commodo tortor efficitur ipsum accumsan, in tincidunt ex lacinia. Quisque pretium quam in mauris interdum ornare quis ut arcu. Donec tristique, risus et placerat ornare, odio metus posuere eros, ut pretium eros dui eget nisi. Proin volutpat luctus arcu, quis molestie urna faucibus feugiat. Aliquam at dui odio. Fusce ut tristique ligula. Sed eu est ante. Donec tempus vestibulum risus, eget sollicitudin lectus aliquet accumsan. Vestibulum pharetra at sapien eu egestas. Quisque tempus neque at orci consectetur efficitur. Nunc ultrices risus mauris, a fermentum erat efficitur at. Aenean laoreet at leo ut pretium. Quisque sodales hendrerit velit id malesuada. Praesent id rutrum velit.

Morbi quis elementum arcu. Vestibulum quis purus vitae nisi rhoncus vulputate eu vitae tellus. Ut a massa ultrices, facilisis ipsum non, suscipit tellus. Nam condimentum lobortis turpis, consectetur posuere ligula consequat eget. Quisque vulputate consectetur tortor eleifend mattis. Proin luctus malesuada lorem, sed molestie ipsum. Nunc fermentum erat eu elit blandit lacinia. Nulla posuere auctor magna, id volutpat sapien feugiat ac.

Quisque ut dignissim nunc. Nulla facilisi. Nunc nibh ex, pulvinar ut augue in, iaculis hendrerit nibh. Phasellus eu diam ligula. Vestibulum dolor felis, facilisis et sodales non, semper nec magna. Phasellus sapien lacus, dignissim in lacus faucibus, pellentesque tempus sem. Pellentesque sit amet ultricies quam. Ut lacus urna, placerat eget leo eget, ullamcorper bibendum dui. Morbi ac varius tortor. Morbi nec ante non eros aliquam vehicula. Proin enim nisl, maximus quis turpis in, malesuada auctor diam. Quisque at elit finibus, consequat enim rhoncus, faucibus felis. Aliquam orci lacus, suscipit eu sagittis eget, consectetur efficitur purus. In ac metus nulla.

Duis a libero massa. Suspendisse quis nibh eu dolor euismod tincidunt iaculis id turpis. Suspendisse eros quam, molestie at dapibus vel, faucibus vel nibh. Sed pretium magna vel purus fringilla blandit nec sed erat. Cras metus leo, iaculis a pharetra ultrices, dignissim vel ante. In non interdum arcu. Maecenas tincidunt consequat felis, at viverra arcu varius sed. Praesent non vehicula neque. In in mi quis ex vehicula euismod ut accumsan nisl.

Aliquam in mattis dolor. Aliquam efficitur suscipit est, sed consequat ex lacinia quis. Duis scelerisque massa quis metus ornare posuere. Donec accumsan tellus id iaculis feugiat. Cras est eros, pellentesque quis erat eget, semper pharetra nisi. Quisque sollicitudin ante dui, id ultrices elit bibendum nec. Vivamus ac vulputate nibh. Suspendisse id tortor varius, blandit arcu nec, vestibulum neque.

Donec elementum metus non magna luctus ornare. Sed aliquet est eros, vitae maximus felis blandit id. Praesent tempus tincidunt massa, sed rutrum tellus ornare et. Integer interdum quam ex, eget efficitur tellus porta vitae. Duis id mi nulla. Phasellus convallis nibh sed justo efficitur ullamcorper. Praesent porta massa risus, eu vehicula dui ornare sit amet. Etiam aliquet orci quis dui hendrerit, nec sagittis mi aliquam. Nullam commodo arcu at ex gravida, quis consequat risus tincidunt. Fusce varius auctor augue ac tincidunt. Ut rutrum pretium odio, nec condimentum risus molestie et. Proin ante velit, euismod id tellus nec, mattis accumsan magna. Vivamus sollicitudin leo eu risus congue, at ultrices tellus maximus.

In sit amet sagittis tortor, sit amet eleifend enim. Quisque ac scelerisque lacus, commodo placerat enim. Quisque finibus quis purus eu pharetra. Praesent feugiat justo ante, quis auctor augue interdum dapibus. Ut commodo purus tempor erat hendrerit bibendum. Praesent tempor nibh sapien, ac feugiat augue posuere quis. Sed vitae porttitor diam, convallis dapibus dui. Nunc maximus pellentesque nunc, et congue dui malesuada quis. Praesent non metus vel metus iaculis lacinia at eget dui. Nullam et sodales lorem. Curabitur quis euismod augue, sit amet egestas velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut nisi vel magna bibendum semper in id nulla. Curabitur porta laoreet nibh non imperdiet.

Phasellus nec lacus ex. Nunc tempor felis eu mi lobortis, in facilisis erat ultrices. Sed tincidunt tellus vel ipsum finibus, et sagittis ex lacinia. Quisque eu ipsum sem. Mauris vitae ipsum quis purus fermentum condimentum. Proin aliquam nisl justo, et elementum tortor sagittis vitae. Quisque urna massa, efficitur nec lorem non, commodo tincidunt est. Cras auctor justo at pellentesque vestibulum. Nullam interdum, lacus a dictum accumsan, nunc risus tempus dolor, in gravida ante tellus et orci. Etiam vitae maximus ipsum. Nullam pulvinar dui id sem sagittis varius. Praesent id arcu sed lectus lacinia gravida nec eget justo.

Vestibulum sodales orci ac mollis auctor. Donec porttitor efficitur malesuada. Duis pulvinar eleifend quam sit amet aliquam. Nulla vel sapien vulputate, scelerisque quam eleifend, viverra diam. Proin ultricies turpis eget tellus condimentum pretium. In scelerisque, eros et blandit condimentum, ligula elit molestie nulla, vitae cursus libero mi et eros. Nullam mollis eros a condimentum commodo. In ac viverra tellus. Fusce egestas ante condimentum, pretium purus ac, varius ante.

Quisque lectus mi, finibus in mauris vel, malesuada porttitor orci. Nullam elit erat, elementum vel semper at, dictum vitae justo. Etiam pretium fringilla lacinia. Nam venenatis quam non lorem ornare tempor. Donec ut tincidunt sapien. In id aliquet ante. Maecenas fermentum dignissim aliquet. Etiam pulvinar non metus at blandit. Sed viverra augue ac eros viverra, a imperdiet mi pretium. Vivamus mattis justo mi, at dignissim lectus lobortis non.

Pellentesque lorem justo, sollicitudin sagittis pulvinar a, consequat vitae ante. Nunc vel ultricies odio. Nam nec enim ullamcorper, consequat sem id, efficitur nulla. Curabitur et mattis nisl. Mauris pharetra magna quis justo elementum vehicula. Nam ipsum neque, vestibulum non ex in, tempor accumsan diam. Vestibulum vitae augue vel sem aliquam porta. Nulla luctus mattis massa vitae pellentesque. Vivamus feugiat, sem a scelerisque placerat, sem neque tempus lorem, non pharetra odio tellus sit amet ligula. Nulla pretium, velit in hendrerit accumsan, ex leo rutrum quam, a laoreet tortor diam quis purus. Donec malesuada mollis dictum. Integer in purus ut turpis dictum auctor non congue mi. Sed in finibus orci. Aenean efficitur ante vulputate, imperdiet lectus ut, porta neque. Morbi pharetra risus condimentum lobortis iaculis. Donec imperdiet quam urna.

Morbi malesuada dolor sit amet ipsum tincidunt, aliquet vulputate mauris porta. Duis accumsan sed eros vitae tempus. In vitae nisi purus. Mauris ut tristique mauris. Donec convallis pulvinar viverra. Morbi gravida tristique urna, quis porta neque rhoncus et. In ac dui pellentesque, porttitor enim et, elementum arcu. Praesent sit amet erat enim. Nullam eu leo tempus, rutrum ante in, interdum leo. Vivamus vitae ullamcorper eros. Curabitur dictum consequat est, eget egestas magna sodales et. Sed et magna quis nisi mollis interdum.

Nulla condimentum scelerisque ante nec ullamcorper. Duis varius, urna ut hendrerit convallis, lacus ex interdum lorem, sed ultrices nisl nisi quis ex. Vestibulum auctor pulvinar nunc, ut suscipit massa. Maecenas vitae scelerisque diam, ut convallis nulla. Quisque blandit ante nec nisi commodo eleifend. Phasellus dictum euismod ultricies. Nunc eu leo ultrices, aliquam purus ac, tristique odio. Phasellus ac leo rhoncus, posuere leo eu, sagittis velit. Nullam dapibus maximus ligula ut lacinia.

Vivamus vulputate finibus congue. Ut aliquam turpis ut mi suscipit, eget mattis est suscipit. Maecenas libero urna, sollicitudin vitae tortor condimentum, congue suscipit erat. Ut gravida, dolor at interdum molestie, lorem tellus semper nibh, quis vehicula nulla lorem ut erat. Integer nec tempus odio. Ut quam quam, aliquam sit amet vehicula eget, tempor non nulla. Donec non tellus non turpis consectetur molestie. Donec mauris massa, eleifend a fringilla sit amet, eleifend a orci. Nulla dictum ante ex, id viverra sapien auctor ultrices. Maecenas elementum mattis augue ut feugiat. Sed finibus at diam non bibendum. Nam nec luctus nibh. Donec sem dui, iaculis in fermentum id, dignissim eu neque. Sed nec tellus nec est euismod dapibus. Etiam tristique mattis ante, vitae tincidunt ipsum.

Curabitur suscipit enim vitae ipsum sodales fermentum. Nulla ullamcorper mauris id gravida consequat. Fusce accumsan ex ac tortor scelerisque placerat. Nullam vehicula, est a congue tempus, magna neque sodales magna, vel mollis augue elit eget ex. Aliquam rutrum sit amet leo vitae pretium. Suspendisse id convallis mi. Sed quis ultrices lectus. Quisque eu erat id sapien viverra ultricies aliquam et nibh. Suspendisse potenti.

Nunc tellus justo, bibendum ac dapibus nec, tempor id nunc. Vestibulum non eleifend nisi. Pellentesque eget rutrum elit. Duis lorem dui, feugiat id mattis ut, viverra a dui. Praesent molestie varius lorem, tempor pellentesque est tristique in. Suspendisse lacinia efficitur suscipit. Fusce in vehicula elit.

Pellentesque non diam ornare, fringilla nulla vel, sollicitudin dolor. Aenean non tortor auctor, gravida ex blandit, tincidunt dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus iaculis augue sed lorem laoreet tristique. Quisque fermentum quam et felis interdum, sed elementum ipsum laoreet. Phasellus placerat eu odio eget iaculis. Praesent malesuada blandit enim, sit amet sodales felis dignissim id. Sed imperdiet sodales orci ac fringilla. Nam pretium ante magna, vitae volutpat mauris faucibus sed. Donec imperdiet nibh libero, a bibendum risus faucibus vel. Donec ullamcorper at augue quis malesuada. Aliquam et nisl mi.

Integer id ante tempus, venenatis nulla ut, venenatis velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam feugiat egestas tortor, eu lobortis eros mollis sed. Nam vel lectus ipsum. Donec sagittis quam dapibus finibus euismod. Morbi laoreet nisl diam, at congue purus consectetur a. Pellentesque commodo malesuada mi non pellentesque. Maecenas vel lacus lacinia, commodo velit in, fermentum orci. Fusce sed auctor ante, et accumsan velit. Integer risus nisi, rhoncus sit amet suscipit ac, lobortis a enim. Aliquam ex arcu, porta volutpat aliquam nec, rhoncus vitae risus.

In rhoncus, justo at commodo consequat, quam velit vulputate nulla, malesuada faucibus felis lorem id ex. Suspendisse convallis molestie ultricies. Aenean quis commodo mi. Sed vitae egestas felis. Donec in lorem a urna tristique laoreet. Cras interdum, velit ut congue eleifend, mauris turpis tristique tortor, et ultricies magna nulla nec sapien. Mauris non tempor ex, nec vestibulum mi. Donec vitae consequat mi. Vivamus in erat vitae magna mattis euismod id id nulla. Etiam accumsan tortor orci, a pellentesque enim porttitor at. Phasellus aliquam augue sem, non suscipit ipsum fringilla sed.

Pellentesque vitae leo odio. Duis ac tempus velit. Sed sit amet orci lacus. Sed commodo sodales ligula, in blandit urna ultricies eu. Ut fringilla risus vel massa pharetra, eu volutpat nulla tincidunt. Curabitur sapien ipsum, suscipit eu interdum eget, bibendum at sem. Cras maximus, ex ac accumsan molestie, nunc libero fermentum ex, sed posuere mi eros nec est. Morbi vestibulum, lorem at accumsan cursus, nisi purus tincidunt lectus, in dictum ante tellus at nulla. In ultrices, lacus at gravida scelerisque, metus dui sollicitudin sapien, quis faucibus magna est id nibh. Vivamus facilisis aliquam odio vulputate malesuada. Sed hendrerit urna dapibus sapien feugiat gravida. Vivamus ac nisi sed purus fermentum pulvinar. Duis turpis libero, laoreet sit amet dolor non, dapibus imperdiet tortor.

Vivamus ac quam lobortis, pretium nulla vel, sagittis ante. Quisque suscipit, velit ac interdum dictum, nulla turpis ultricies orci, sit amet porta diam ipsum id nibh. Sed pretium, metus id tincidunt suscipit, lorem massa scelerisque nisl, in pharetra nulla orci ultricies orci. Vestibulum accumsan pellentesque odio, et rutrum magna dignissim id. Curabitur vitae nunc a lorem tristique commodo. Duis suscipit, tortor ac mattis dictum, ex purus condimentum purus, at rhoncus lectus elit non nibh. Etiam fringilla pretium pharetra. Proin luctus massa pretium, lacinia mi quis, ultricies sem. Pellentesque nec enim a ex commodo sollicitudin nec quis risus. Aenean non orci lacus. Nunc erat justo, facilisis ut scelerisque sed, ornare id quam. Duis sollicitudin ante luctus venenatis viverra. Proin faucibus sed diam auctor scelerisque. Curabitur gravida purus diam, in euismod felis vehicula sit amet.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent risus diam, rhoncus at est ut, scelerisque blandit augue. Sed molestie porttitor tempor. Nunc sed elementum eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean cursus consequat lectus, tempus accumsan odio interdum eleifend. Mauris ac magna erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc eu laoreet sapien. Donec vestibulum molestie ligula, viverra tincidunt lectus semper sed. Fusce vehicula diam sapien, et volutpat urna maximus nec. Nam ac accumsan ligula, malesuada mattis dui. Vivamus auctor tempor tellus. Nullam venenatis viverra interdum.

Nullam nec neque sagittis velit bibendum convallis. Nullam condimentum, turpis in euismod ultrices, arcu libero luctus ex, vestibulum bibendum massa neque pellentesque libero. Cras quis quam lectus. Duis egestas lacus a tempor fringilla. Morbi condimentum varius ipsum vel condimentum. Aenean tempus condimentum pulvinar. Fusce blandit auctor enim et accumsan. Suspendisse auctor lacus arcu, vitae imperdiet velit vestibulum tristique. Integer maximus eu mauris suscipit cursus. Pellentesque blandit nisl quis luctus pellentesque. Nam mattis magna libero, ullamcorper eleifend eros tincidunt ac.

Pellentesque eu ullamcorper diam. Etiam in lorem at orci tincidunt finibus id a turpis. Donec interdum massa id augue cursus consequat. Nam vehicula eu nisl vel malesuada. Ut enim mi, aliquam et ullamcorper in, lacinia ac leo. Ut ut quam odio. Mauris euismod justo ac turpis congue, pharetra lobortis libero dictum. Maecenas finibus, quam eget porta interdum, ante erat imperdiet tellus, vel pretium est ligula at augue. Curabitur hendrerit quam ac turpis finibus rutrum. Vivamus vehicula mollis magna.

Ut et felis vel turpis tempus eleifend. Mauris tristique cursus massa non iaculis. Nunc blandit sem nec ultricies ultrices. Phasellus scelerisque condimentum dui vitae tempor. Mauris nec eros dolor. Proin quis diam convallis, ornare risus nec, sagittis erat. Curabitur nec placerat nisi, ultrices euismod leo.

Proin elit mauris, imperdiet eget lacus nec, rhoncus vestibulum diam. Etiam molestie, diam sed aliquet porta, velit quam suscipit est, et cursus libero purus sit amet leo. Praesent varius blandit mollis. Praesent vehicula id neque ut aliquam. Sed quis orci nisi. Nam quis massa ac dui blandit ornare ac et nunc. Praesent ultrices mi dui, gravida laoreet orci facilisis ut. Cras pharetra enim ligula, non tempus est finibus a.

Aenean ut nisl et magna mollis ullamcorper. Fusce congue orci ipsum, non lacinia erat ultrices et. Sed molestie metus urna, non viverra eros consectetur eget. Donec elementum leo odio, eu pellentesque mi pharetra sed. Vestibulum ultrices erat a quam tempor tempor. Donec lobortis magna vitae tellus feugiat, quis pulvinar velit condimentum. Ut ornare elit a quam hendrerit rutrum. Nulla et leo vehicula, euismod massa non, porttitor orci. Fusce quis faucibus ipsum, posuere aliquet nulla.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus id vehicula magna. Nam vestibulum scelerisque felis, eu sodales dolor placerat eu. Donec eget mi in orci ornare luctus. Aenean tincidunt ipsum eget ipsum interdum euismod. Quisque elit lectus, porta id elit vel, dapibus accumsan orci. Vivamus ante risus, feugiat et sem nec, interdum porttitor lacus. Maecenas et risus vel diam cursus tristique eu a metus.

Cras ac nibh at velit pretium elementum. Morbi sit amet consequat arcu. Duis consectetur lorem urna, vel tempor urna rutrum ut. Praesent ultricies, massa non ultricies euismod, massa neque efficitur purus, non tincidunt dolor nibh sit amet nulla. Vivamus bibendum erat sed commodo dignissim. Fusce ultrices purus vitae lacus accumsan malesuada. Fusce tempor lobortis imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean condimentum rhoncus lectus sit amet faucibus. Phasellus nec elit vehicula, feugiat nisl quis, interdum felis. Nunc eget hendrerit lacus. Ut auctor interdum mi, vel convallis neque. Aenean in nunc ac ligula lobortis bibendum id vitae augue. Nunc eros magna, placerat semper tempor vitae, cursus in lectus.

Nam sollicitudin nisi et ornare tincidunt. Duis mauris lacus, pharetra nec velit id, pulvinar tempor dui. Cras nec magna ac nisl volutpat ornare sed quis urna. Curabitur rutrum augue nec nisl placerat iaculis. In fringilla a metus eget congue. Nam tempor purus placerat lacus maximus, non vestibulum turpis ultrices. Fusce elementum at arcu sed lobortis. Donec placerat dapibus lorem, a gravida ante placerat gravida. Curabitur consectetur, justo sed tincidunt rutrum, magna metus pretium quam, vel facilisis augue ipsum ut elit. Ut varius tellus eget dui cursus tempus. Nullam eget hendrerit nisl. Vestibulum pulvinar ac dolor vitae volutpat. Duis tempor ultrices tortor, vel placerat diam maximus sit amet. Aliquam tincidunt mi condimentum erat mattis congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Sed quis lectus porta neque tristique finibus. Etiam quis tortor ex. Sed tortor dolor, malesuada ac ligula quis, ultrices efficitur eros. Ut congue lectus vitae turpis sollicitudin facilisis. Nunc egestas sagittis leo et sodales. Curabitur ante enim, rhoncus sit amet quam vel, iaculis pellentesque nibh. Curabitur sed nulla eros. Nunc id scelerisque orci, eget condimentum mauris. Ut sit amet egestas ligula. Praesent aliquam nibh metus. Donec mollis, sapien sed iaculis faucibus, odio ante scelerisque ligula, ut auctor sapien nulla eu massa. Morbi vel orci at leo ultrices cursus. Praesent nec eros nec lectus facilisis sodales. Maecenas tristique iaculis massa, non lacinia felis tempor in. Nam mattis augue ipsum, nec fermentum eros pulvinar vitae. Proin consequat ligula a diam iaculis, in consectetur metus pulvinar.

Etiam consectetur ante venenatis, fermentum odio eget, gravida lacus. Morbi ut tortor quis nulla porta aliquam. Curabitur malesuada mi vel lectus dictum, non bibendum lacus auctor. Sed sed interdum libero, a posuere nunc. Mauris ut augue sed mauris faucibus convallis. Phasellus id dapibus felis, non fermentum eros. Vestibulum eleifend nisi sed tempus facilisis.

Phasellus tristique scelerisque leo in viverra. Morbi eget nibh dui. Nam non arcu dui. Fusce convallis orci quis orci elementum tempus. Curabitur facilisis facilisis lacinia. Nulla dapibus scelerisque mi id molestie. Fusce in arcu in dui vulputate fringilla. Donec non metus vel nisi consequat aliquam et nec lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse eu eros sed eros rhoncus fermentum nec eu ante. Vivamus venenatis sapien ut nisi malesuada, eget aliquet risus finibus. Integer posuere lectus sed semper vulputate. Mauris blandit efficitur diam sed aliquam.

Nullam tortor arcu, finibus et maximus volutpat, efficitur eu velit. Quisque vel fermentum mauris. Curabitur elementum ligula lorem, eget malesuada augue posuere vitae. Etiam dapibus sed dui non bibendum. Proin in purus sed nulla bibendum varius quis ac elit. Quisque ac enim ut lectus pretium blandit vitae eget lectus. Nullam at velit sodales, facilisis risus at, sagittis nisi. Pellentesque tempor volutpat tellus, et euismod lacus consequat vel. Fusce at congue nunc. Quisque gravida lorem ac elementum dapibus. Etiam dictum iaculis orci at viverra. Donec tempus, diam in congue malesuada, nulla ipsum tincidunt arcu, at tempor nunc purus in mauris. Mauris non ante mollis, venenatis erat ac, mattis libero. Sed molestie erat ligula, quis molestie est tempor vel.

Curabitur euismod nisi sem, eget ornare nibh malesuada et. Vivamus nisl massa, blandit ac ultrices eget, euismod eu odio. In hac habitasse platea dictumst. Donec sed maximus velit, sit amet auctor justo. In elit sem, placerat in justo ac, bibendum consectetur tortor. Fusce euismod odio sit amet lectus dapibus, nec laoreet odio eleifend. Vestibulum dapibus auctor purus, nec commodo risus. Aenean dictum lacus sit amet ante mollis luctus. Curabitur in orci euismod, pretium justo ac, venenatis velit. Aenean id hendrerit lacus. Proin commodo ac nisl nec feugiat. Suspendisse a velit pellentesque, tristique elit imperdiet, pharetra ipsum. Morbi id diam vulputate odio faucibus ullamcorper. Curabitur lectus augue, blandit non orci sed, vulputate vulputate risus.

Curabitur ullamcorper faucibus urna. Morbi quis consequat purus, nec faucibus sapien. Integer a luctus lacus. Curabitur vehicula velit nisl, in luctus felis cursus ac. Curabitur eu felis semper, blandit risus in, pharetra mi. Nulla facilisi. Etiam auctor ullamcorper libero, malesuada interdum magna cursus eget. Nunc venenatis leo euismod, maximus justo at, dapibus magna. Phasellus a urna ultricies, egestas orci quis, semper odio. Aliquam consectetur dui posuere pretium condimentum. Maecenas at pharetra ex. Quisque orci lorem, finibus ornare nunc sit amet, sollicitudin egestas tellus. Praesent eget magna vel arcu commodo dignissim.

Ut pulvinar laoreet enim vel sagittis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed egestas finibus metus, eget pretium sapien convallis vitae. Donec sagittis ligula id rhoncus porttitor. Morbi et sagittis enim. Sed posuere tempus placerat. Aenean dolor mi, placerat ac scelerisque bibendum, lacinia quis ante. Maecenas maximus vel mi ac blandit. Nulla pulvinar dolor sit amet orci eleifend tempor. Sed consequat dui at velit iaculis, eget consectetur ligula interdum. Suspendisse nec convallis lorem, quis eleifend massa. Curabitur cursus nulla vitae finibus tincidunt. Maecenas a nisi ac orci congue consectetur. Cras ac massa id velit tincidunt efficitur et eu velit. Nam porttitor cursus sem eget blandit.

Vestibulum eros tortor, bibendum a lorem eget, molestie luctus diam. Fusce viverra viverra pretium. Duis non porta augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam ornare vel lorem at convallis. In hac habitasse platea dictumst. Nulla eget mi non lectus commodo tempus. Nulla tincidunt enim et rutrum malesuada. Phasellus rhoncus velit eu neque tincidunt tincidunt.

Nunc scelerisque blandit odio. Maecenas tempor semper dolor a laoreet. Morbi arcu neque, gravida ut sapien at, aliquam condimentum dolor. Etiam euismod justo vel augue fringilla, venenatis commodo felis semper. Ut ut dui ipsum. Nam volutpat sem quis euismod facilisis. Curabitur ligula sem, faucibus sit amet lacinia a, ullamcorper a est. Phasellus arcu nisi, commodo sed purus vel, commodo cursus magna. Nam pharetra volutpat metus quis congue. Cras facilisis sem nec ligula mattis, vitae tempor sapien viverra. Nullam dictum fringilla nulla eu commodo. Praesent quis condimentum enim, sed rutrum tortor.

Integer egestas neque condimentum lorem tempor posuere. Nunc lacinia rhoncus felis eget fermentum. Vivamus convallis ut lorem nec euismod. Vestibulum a posuere tellus. Nullam lobortis ante odio. Etiam aliquet euismod nisi. Maecenas vel viverra dui. Vestibulum finibus bibendum auctor. Donec ex metus, malesuada varius molestie at, convallis ut leo. Duis magna enim, pulvinar a felis non, tincidunt mattis elit. Maecenas convallis lacus sit amet lacinia bibendum. Curabitur vel tristique tortor. Fusce porttitor leo semper lectus sagittis, a ultrices justo commodo. Praesent nec eros semper, sollicitudin velit sit amet, porta turpis. 
    </Container>
  )
}

const Container = styled.div`
    width: 100%;
    min-height: 100%;
    border-radius: 0 20px 20px 0;
    border: 5px solid transparent;
    border-left:0;
    background: linear-gradient(#FBC1BF,#A8CEFF) border-box;
    overflow-y: scroll;
    padding-top: 10px;
    padding-bottom: 10px;
`; 

export {Container}